### ISSUE TITLE
✨[FEAT] - 서버 연결 세팅

### ISSUE THREAD

**Issue by dlwns33** [TeamFILL-IN/Fill-iOS#48]
# 👀 이슈 (issue)

서버 연결을 위한 초기세팅을 진행합니다.

# 📸 to-do

- [x] 플러그인 연결
- [x] API 파일 만들기
- [x] Service 파일 만들기
- [x] 쓰는 방법 주석 처리
